FROM adoptopenjdk:17-jdk-hotspot
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
ARG JAR_FILE=prevalentware/gradle/wrapper/*.jar
COPY ${JAR_FILE} gradle-wrapper.jar
ENTRYPOINT ["java", "-jar", "/gradle-wrapper.jar"]